export const basicComponents = [
  {
    type: 'input',
    icon: 'icon-input',
    hasLabel: true,
    hasModel: true,
    options: {
      width: '100%',
      defaultValue: '',
      required: false,
      dataType: 'text',
      pattern: '',
      placeholder: '',
      disabled: false,
      maxlength: -1,
      showWordLimit: false,
    },
  },

  {
    type: 'button',
    icon: 'icon-input',
    options: {
      title: 'Button',
      variant: 'secondary',
      pill: false,
      squared: false,
      disabled: false,
      block: false,
      customClass: '',
    },
  },

  {
    type: 'textarea',
    icon: 'icon-diy-com-textarea',
    options: {
      width: '100%',
      defaultValue: '',
      required: false,
      disabled: false,
      pattern: '',
      placeholder: '',
      maxlength: -1,
      showWordLimit: false,
    },
  },
  {
    type: 'number',
    icon: 'icon-number',
    hasLabel: true,
    options: {
      width: '',
      required: false,
      defaultValue: 0,
      min: '',
      max: '',
      step: 1,
      disabled: false,
      controlsPosition: '',
    },
  },
  {
    type: 'radio',
    icon: 'icon-radio-active',
    options: {
      inline: false,
      defaultValue: '',
      showLabel: false,
      options: [
        {
          value: 'Option 1',
          label: 'Option 1',
        },
        {
          value: 'Option 2',
          label: 'Option 2',
        },
        {
          value: 'Option 3',
          label: 'Option 3',
        },
      ],
      required: false,
      width: '',
      remote: false,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
      disabled: false,
    },
  },
  {
    type: 'checkbox',
    icon: 'icon-check-box',
    hasLabel: true,
    options: {
      inline: false,
      defaultValue: [],
      showLabel: false,
      options: [
        {
          value: 'Option 1',
        },
        {
          value: 'Option 2',
        },
        {
          value: 'Option 3',
        },
      ],
      required: false,
      width: '',
      remote: false,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
      disabled: false,
    },
  },
  {
    type: 'time',
    icon: 'icon-time',
    hasLabel: true,
    options: {
      defaultValue: '21:19:56',
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      isRange: false,
      arrowControl: true,
      format: 'HH:mm:ss',
      required: false,
      width: '',
    },
  },
  {
    type: 'date',
    icon: 'icon-date',
    hasLabel: true,
    options: {
      defaultValue: '',
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      type: 'date',
      format: 'yyyy-MM-dd',
      timestamp: false,
      required: false,
      width: '',
    },
  },
  {
    type: 'rate',
    icon: 'icon-pingfen1',
    options: {
      defaultValue: null,
      max: 5,
      disabled: false,
      required: false,
    },
  },
  {
    type: 'color',
    icon: 'icon-color',
    options: {
      defaultValue: '',
      disabled: false,
      required: false,
    },
  },
  {
    type: 'select',
    icon: 'icon-select',
    options: {
      defaultValue: '',
      multiple: false,
      disabled: false,
      placeholder: '',
      required: false,
      showLabel: false,
      width: '',
      options: [
        {
          value: 'Option 1',
        },
        {
          value: 'Option 2',
        },
        {
          value: 'Option 3',
        },
      ],
      remote: false,
      filterable: false,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
    },
  },
  {
    type: 'switch',
    icon: 'icon-switch',
    options: {
      defaultValue: false,
      required: false,
      disabled: false,
    },
  },
  {
    type: 'slider',
    icon: 'icon-slider',
    options: {
      defaultValue: 0,
      disabled: false,
      required: false,
      min: 0,
      max: 100,
      step: 1,
      showInput: false,
      range: false,
      width: '',
    },
  },
  {
    type: 'text',
    icon: 'icon-wenzishezhi-',
    options: {
      defaultValue: 'This is a text',
      customClass: '',
    },
  },
  {
    type: 'dropdown',
    icon: 'icon-input',
    items: [],
    options: {
      text: 'New dropdown',
      block: false,
      dropleft: false,
      dropright: false,
      dropup: false,
      noCaret: false,
      noFlip: false,
      offset: null,
      right: false,
      split: false,
      variant: null,
      customClass: '',
      disabled: false,
    },
  },
]

export const advanceComponents = [
  {
    type: 'blank',
    icon: 'icon-zidingyishuju',
    options: {
      defaultType: 'String',
    },
  },
  {
    type: 'imgupload',
    icon: 'icon-tupian',
    options: {
      defaultValue: [],
      size: {
        width: 100,
        height: 100,
      },
      width: '',
      tokenFunc: 'funcGetToken',
      token: '',
      domain: 'https://tcdn.form.making.link/',
      disabled: false,
      length: 8,
      multiple: false,
      isQiniu: false,
      isDelete: false,
      min: 0,
      isEdit: false,
      action: 'https://tools-server.making.link/api/transfer',
    },
  },
  {
    type: 'editor',
    icon: 'icon-fuwenbenkuang',
    options: {
      defaultValue: '',
      width: '',
    },
  },
  {
    type: 'cascader',
    icon: 'icon-jilianxuanze',
    options: {
      defaultValue: [],
      width: '',
      placeholder: '',
      disabled: false,
      clearable: false,
      remote: true,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
        children: 'children',
      },
      remoteFunc: '',
    },
  },
  {
    type: 'view-list',
    icon: 'icon-table',
    hasModel: true,
    options: {
      defaultValue: [],
      hover: true,
      striped: true,
      selectable: true,
      selectMode: 'single',
      fields: [
        { key: 'id', label: 'Id', sortable: false },
        { key: 'name', label: 'Name', sortable: true },
      ],
      sort: {
        sortBy: null,
        sortDesc: false,
      },
      perPage: 25,
      disabled: false,
      customClass: 'mb-2',
      bodyClass: '',
    },
  },
  {
    type: 'pagination',
    icon: 'icon-input',
    options: {
      defaultValue: 1,
      defaultTotal: 100,
      perPage: 25,
      align: 'right',
      customClass: 'my-0',
      disabled: false,
    },
  },
]

export const layoutComponents = [
  {
    type: 'container',
    icon: 'icon-grid-',
    layout: true,
    list: [],
    options: {
      fluid: null,
      customClass: '',
    },
  },
  {
    type: 'grid',
    icon: 'icon-grid-',
    layout: true,
    columns: [
      {
        cols: null,
        sm: null,
        md: null,
        lg: null,
        xl: null,
        offset: null,
        offsetSm: null,
        offsetMd: null,
        offsetLg: null,
        offsetXl: null,
        order: null,
        orderSm: null,
        orderMd: null,
        orderLg: null,
        orderXl: null,
        alignSelf: null,
        tag: 'div',
        customClass: '',
        list: [],
      },
    ],
    options: {
      noGutters: false,
      alignH: null,
      alignV: null,
      alignContent: null,
      cols: null,
      colsSm: null,
      colsLg: null,
      colsXl: null,
      tag: 'div',
      customClass: '',
    },
  },
  {
    type: 'card',
    icon: 'icon-grid-',
    layout: true,
    list: [],
    options: {
      title: '',
      subTitle: '',
      customClass: '',
    },
  },
  {
    type: 'toolbar',
    icon: 'icon-input',
    layout: true,
    list: [],
    options: {
      keyNav: false,
      customClass: '',
    },
  },
  {
    type: 'btnGroup',
    icon: 'icon-input',
    layout: true,
    list: [],
    options: {
      vertical: false,
      customClass: '',
    },
  },
  {
    type: 'collapse',
    icon: 'icon-input',
    hasModel: true,
    layout: true,
    list: [],
    options: {
      defaultValue: true,
      accordion: null,
      appear: false,
      customClass: '',
    },
  },
  {
    type: 'inputGroup',
    icon: 'icon-input',
    layout: true,
    list: [],
    prependList: [],
    options: {
      customClass: '',
    },
  },
]
