// Catalogs import
const indexRouter = require('./index')
const userRouter = require('@catalogs/users/routes')
const roleGroupRouter = require('@catalogs/roleGroups/routes')
const userSettingItemsRouter = require('@catalogs/userSettingItems/routes')
const userSettingRouter = require('@registers/userSettings/routes')
const firmsRouter = require('@catalogs/firms/routes')
const executorRoleRouter = require('@catalogs/executorRoles/routes')
const taskTemplateRouter = require('@catalogs/taskTemplates/routes')
const productRouter = require('@catalogs/products/routes')
const projectRouter = require('@catalogs/projects/routes')
const discountRouter = require('@documents/discounts/routes')
const employeeRouter = require('@catalogs/employees/routes')
const customerRouter = require('@catalogs/counterparties/routes')
const parameterRouter = require('@catalogs/constructor/routes/parameter')
const parameterValueRouter = require('@catalogs/constructor/routes/parameterValue')
const expressionVariableRouter = require('@catalogs/constructor/routes/expressionVariable')
const emailTemplateRouter = require('@catalogs/emailTemplates/routes')
const documentNumeratorRouter = require('@registers/documentNumerators/routes')
const reclamationSubjectRouter = require('@catalogs/reclamationSubjects/routes')
const reclamationStatusGroupRouter = require('@catalogs/reclamationStatusGroups/routes')
const reclamationStatusRouter = require('@catalogs/reclamationStatuses/routes')
const reclamationTypeRouter = require('@catalogs/reclamationTypes/routes')
const reclamationReasonsRouter = require('@catalogs/reclamationReasons/routes')
const deliveryTypesRouter = require('@catalogs/deliveryTypes/routes')
const costArticlesRouter = require('@catalogs/costArticles/routes')
const uomRouter = require('@catalogs/unitsOfMeasure/routes')
const currencyRouter = require('@catalogs/currencies/routes')
const salesOrderStatusRouter = require('@catalogs/salesOrderStatuses/routes')
const documentPrefixesRouter = require('@catalogs/documentPrefixes/routes')
const contactPersonRouter = require('@catalogs/contactPersons/routes')
const reclamationPerpetorsRouter = require('@catalogs/reclamationPerpetrator/routes')
const ReclamationClientDemandsRouter = require('@catalogs/reclamationClientDemands/routes')
const reclamationExecutionTypeRouter = require('@catalogs/reclamationExecutionTypes/routes')
const reclamationDecisionRouter = require('@catalogs/reclamationDecisions/routes')
const customerRequestStatusRouter = require('@catalogs/customerRequestStatuses/routes')
const customerRequestTagRouter = require('@catalogs/customerRequestTags/routes')
const interactionStatusRouter = require('@catalogs/interactionStatuses/routes')
const interactionTagRouter = require('@catalogs/interactionTags/routes')
const emailAccountsRouter = require('@catalogs/emailAccounts/routes')
const termOfPaymentRouter = require('@catalogs/termsOfPayment/routes')
const countryRouter = require('@catalogs/countries/routes')
const eventRouter = require('@documents/events/routes')
const eventTypeRouter = require('@catalogs/eventTypes/routes')
const eventStatusRouter = require('@catalogs/eventStatuses/routes')
const standingRouter = require('@catalogs/standings/routes')
const emailLabelsRouter = require('@catalogs/emailLabels/routes')
const assortmentRouter = require('@catalogs/assortments/routes')
const boxRouter = require('@catalogs/boxes/routes')
const warehouseRouter = require('@catalogs/warehouses/routes')
const carrierRouter = require('@catalogs/carriers/routes')
const controlCompanyRouter = require('@catalogs/controlCompanies/routes')
const driverRouter = require('@catalogs/drivers/routes')
const vendorsAndCustomerRouter = require('@catalogs/vendorsAndCustomers/routes')
const mineRouter = require('@catalogs/mines/routes')
const positionRouter = require('@catalogs/positions/routes')
const weighingStation = require('@catalogs/weighingStations/routes')
const scale = require('@catalogs/scales/routes')
const scaleProtocol = require('@catalogs/scaleProtocols/routes')
const schemeOfCargo = require('@catalogs/schemesOfCargo/routes')
const ship = require('@catalogs/ships/routes')
const trackModel = require('@catalogs/trackModels/routes')
const vehicle = require('@catalogs/vehicles/routes')
const wharf = require('@catalogs/wharfs/routes')
const workingPlaceRouter = require('@catalogs/workingPlaces/routes')
const userRoleRouter = require('@catalogs/userRoles/routes')
const dispositionStatusRouter = require('@catalogs/dispositionStatuses/routes')
const paymentTypeRouter = require('@catalogs/paymentTypes/routes')
const cashFlowItemRouter = require('@catalogs/cashFlowItems/routes')
const departmentRouter = require('@catalogs/departments/routes')
const accessRestrictionRouter = require('@registers/accessRestrictions/routes')

// Documents import
const customerRequestRouter = require('@documents/customerRequests/routes')
const interactionRouter = require('@documents/interactions/routes')
const taskRouter = require('@documents/tasks/routes')
const salesOrderRouter = require('@documents/salesOrders/routes')
const pricelistRouter = require('@documents/pricelists/routes')
const reclamationRouter = require('@documents/reclamations/routes/reclamation')
const reclamationItemRouter = require('@documents/reclamations/routes/reclamationsItem')
const reclamationEmailRouter = require('@documents/reclamations/routes/reclamationsEmail')

const reclamationCostslRouter = require('@documents/reclamations/routes/reclamationCosts')
const reclamationDeliveryRouter = require('@documents/reclamations/routes/reclamationDelivery')

const reclamationHistoryRouter = require('@documents/reclamations/routes/reclamationsHistory')
const reclamationProductionOrderRouter = require('@documents/reclamations/routes/reclamationsProductionOrder')
const reclamationFileRouter = require('@documents/reclamations/routes/reclamationFile')
const incomingEmailRouter = require('@documents/incomingEmails/routes')
const outgoingEmailRouter = require('@documents/outgoingEmails/routes')
const deliveryOrderRouter = require('@documents/deliveryOrders/routes')
const dispositionRouter = require('@documents/dispositions/routes')
const deliveryNoteRouter = require('@documents/deliveryNotes/routes')
const shipUnloadingRouter = require('@documents/shipsUnloading/routes')
const paymentOperationRouter = require('@documents/paymentOperations/routes')

const bpDefinitions = require('@businessProcesses/definitions/routes')
const bpExemplars = require('@businessProcesses/bp/routes')
const bpHistories = require('@businessProcesses/history/routes')
const calendars = require('@registers/calendars/routes/index')
const calendarEvents = require('@registers/calendarEvents/routes/index')

const accessLogs = require('@config/accessLogs/routes')

// Registers import
const objectVersionRouter = require('@registers/objectVersions/routes')
const objectVersioningSettingRouter = require('@registers/objectVersioningSettings/routes')
const exchangeObjectRouter = require('@registers/exchangeObjects/routes')
const notificationRouter = require('@registers/notifications/routes')
const productParamSettingRouter = require('@registers/productParameterSettings/routes')
const plumbLineRouter = require('@registers/plumbLines/routes')
const inventoryRouter = require('@registers/inventory/routes')
const weightedDispositionRouter = require('@registers/weightedDispositions/routes')
const objectsTimmeTrackingRouter = require('@registers/objectsTimeTracking/routes')
const contactInformationRouter = require('@registers/contactInformation/routes')

// Common modules import
const authRouter = require('@common/auth/routes')
const mailBoxRouter = require('@common/mailbox/routes')
const hes1CSyncRouter = require('@common/exchange/hes1CSync/routes/')

const reportsRouter = require('@modules/reports/routes')
const reportVariantsRouter = require('@registers/reportVariants/routes')

const dashboardRouter = require('@common/dashboard/routes')
const appRouter = require('@common/app/routes')
const navigationRouter = require('@config/navigation/routes')
const appStoreRouter = require('@config/appStores/routes')
const viewSettingsRouter = require('@config/viewSettings/routes')
const userViewSettingsRouter = require('@config/userViewSettings/routes')

module.exports = (app) => {
  app.use(indexRouter)
  app.use(navigationRouter)
  app.use(dashboardRouter)
  app.use(userRouter)
  app.use(authRouter)
  app.use(salesOrderRouter)
  app.use(executorRoleRouter)
  app.use(taskRouter)
  app.use(taskTemplateRouter)
  app.use(productRouter)
  app.use(projectRouter)
  app.use(parameterRouter)
  app.use(parameterValueRouter)
  app.use(employeeRouter)
  app.use(customerRouter)
  app.use(pricelistRouter)
  app.use(discountRouter)
  app.use(uomRouter)
  app.use(currencyRouter)
  app.use(termOfPaymentRouter)
  app.use(countryRouter)
  app.use(accessLogs)
  app.use(userRoleRouter)
  app.use(eventRouter)
  app.use(eventTypeRouter)
  app.use(eventStatusRouter)
  app.use(standingRouter)

  app.use(assortmentRouter)
  app.use(boxRouter)
  app.use(warehouseRouter)
  app.use(carrierRouter)
  app.use(controlCompanyRouter)
  app.use(driverRouter)
  app.use(vendorsAndCustomerRouter)
  app.use(mineRouter)
  app.use(positionRouter)
  // app.use(productForwarder)
  app.use(weighingStation)
  app.use(scale)
  app.use(scaleProtocol)
  app.use(schemeOfCargo)
  app.use(ship)
  app.use(trackModel)
  app.use(vehicle)
  app.use(wharf)
  app.use(workingPlaceRouter)
  app.use(salesOrderStatusRouter)
  app.use(expressionVariableRouter)
  app.use(exchangeObjectRouter)
  app.use(notificationRouter)
  app.use(roleGroupRouter)
  app.use(objectVersionRouter)
  app.use(objectVersioningSettingRouter)
  app.use(firmsRouter)
  app.use(incomingEmailRouter)
  app.use(outgoingEmailRouter)
  app.use(emailTemplateRouter)
  app.use(documentNumeratorRouter)
  app.use(documentPrefixesRouter)
  app.use(dispositionStatusRouter)
  app.use(paymentTypeRouter)
  app.use(cashFlowItemRouter)
  app.use(contactPersonRouter)
  app.use(departmentRouter)
  app.use(paymentOperationRouter)

  //Reclamations module
  app.use(reclamationRouter)
  app.use(reclamationSubjectRouter)
  app.use(reclamationStatusGroupRouter)
  app.use(reclamationStatusRouter)
  app.use(reclamationReasonsRouter)
  app.use(reclamationTypeRouter)
  app.use(deliveryTypesRouter)
  app.use(costArticlesRouter)
  app.use(reclamationExecutionTypeRouter)
  app.use(reclamationDecisionRouter)
  app.use(reclamationItemRouter)
  app.use(reclamationEmailRouter)
  app.use(reclamationCostslRouter)
  app.use(reclamationDeliveryRouter)
  app.use(reclamationHistoryRouter)
  app.use(reclamationProductionOrderRouter)
  app.use(reclamationFileRouter)
  app.use(mailBoxRouter)
  app.use(emailAccountsRouter)
  app.use(ReclamationClientDemandsRouter)
  app.use(reclamationPerpetorsRouter)
  app.use(interactionStatusRouter)
  app.use(interactionTagRouter)
  app.use(interactionRouter)
  app.use(customerRequestRouter)
  app.use(customerRequestStatusRouter)
  app.use(customerRequestTagRouter)
  app.use(deliveryOrderRouter)
  app.use(dispositionRouter)
  app.use(deliveryNoteRouter)
  app.use(shipUnloadingRouter)
  app.use(bpExemplars)
  app.use(bpDefinitions)
  app.use(bpHistories)
  app.use(calendars)
  app.use(calendarEvents)
  app.use(reportsRouter)
  app.use(reportVariantsRouter)
  app.use(appRouter)
  app.use(userSettingItemsRouter)
  app.use(userSettingRouter)
  app.use(productParamSettingRouter)
  app.use(plumbLineRouter)
  app.use(inventoryRouter)
  app.use(weightedDispositionRouter)
  app.use(appStoreRouter)
  app.use(viewSettingsRouter)
  app.use(userViewSettingsRouter)
  app.use(objectsTimmeTrackingRouter)
  app.use(contactInformationRouter)
  app.use(hes1CSyncRouter)
  app.use(emailLabelsRouter)
  app.use(accessRestrictionRouter)
}
